from config import settings
from libs.api_manager._resource_groups.api_resource_groups import alpha_vantage_rapidapi_resouce_group
from libs.api_manager._utils.api import API

# AlphaVantage RapidAPI constants
_ALPHA_VANTAGE_RAPIDAPI_BASE_URL = "https://alpha-vantage.p.rapidapi.com/query"
_ALPHA_VANTAGE_RAPIDAPI_HEADERS = {
    "X-RapidAPI-Key": settings.get("ALPHA_VANTAGE_RAPIDAPI_KEY"),
    "X-RapidAPI-Host": "alpha-vantage.p.rapidapi.com",
}
_ALPHA_VANTAGE_RAPIDAPI_ENDPOINTS = sorted(
    {
        "TIME_SERIES_INTRADAY",
        "TIME_SERIES_DAILY_ADJUSTED",
        "TIME_SERIES_DAILY",
        "TIME_SERIES_WEEKLY_ADJUSTED",
        "TIME_SERIES_WEEKLY",
        "TIME_SERIES_MONTHLY_ADJUSTED",
        "TIME_SERIES_MONTHLY",
        "GLOBAL_QUOTE",
        "SYMBOL_SEARCH",
        "FX_MONTHLY",
        "FX_WEEKLY",
        "FX_DAILY",
        "FX_INTRADAY",
        "CURRENCY_EXCHANGE_RATE",
        "DIGITAL_CURRENCY_MONTHLY",
        "DIGITAL_CURRENCY_WEEKLY",
        "DIGITAL_CURRENCY_DAILY",
        "SMA",
        "EMA",
        "WMA",
        "DEMA",
        "TEMA",
        "TRIMA",
        "KAMA",
        "MAMA",
        "VWAP Premium",
        "T3",
        "MACD Premium",
        "MACDEXT",
        "STOCH",
        "STOCHF",
        "RSI",
        "STOCHRSI",
        "WILLR",
        "ADX",
        "ADXR",
        "APO",
        "PPO",
        "MOM",
        "BOP",
        "CCI",
        "CMO",
        "ROC",
        "ROCR",
        "AROON",
        "AROONOSC",
        "MFI",
        "TRIX",
        "ULTOSC",
        "DX",
        "MINUS_DI",
        "PLUS_DI",
        "MINUS_DM",
        "PLUS_DM",
        "BBANDS",
        "MIDPOINT",
        "MIDPRICE",
        "SAR",
        "TRANGE",
        "ATR",
        "NATR",
        "AD",
        "ADOSC",
        "OBV",
        "HT_TRENDLINE",
        "HT_SINE",
        "HT_TRENDMODE",
        "HT_DCPERIOD",
        "HT_DCPHASE",
        "HT_PHASOR",
    },
)

alpha_vantage_rapidapi = API(
    identifier="alpha_vantage_rapidapi",
    resource_group=alpha_vantage_rapidapi_resouce_group,
    base_url=_ALPHA_VANTAGE_RAPIDAPI_BASE_URL,
    headers=_ALPHA_VANTAGE_RAPIDAPI_HEADERS,
    endpoints=_ALPHA_VANTAGE_RAPIDAPI_ENDPOINTS,
)
